import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

import { jsPDF } from "jspdf";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function downloadAsFile(filename: string, content: string, type: string = 'text/plain') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadAsPDF(filename: string, title: string, content: string) {
  const doc = new jsPDF();
  
  // Set fonts and colors
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  
  // Header
  doc.text(title, 20, 25);
  doc.setLineWidth(0.5);
  doc.line(20, 30, 190, 30);
  
  // Body Content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  
  // Split text into lines to wrap within page width
  const splitContent = doc.splitTextToSize(content, 170);
  let y = 40;
  
  splitContent.forEach((line: string) => {
    if (y > 280) { // Page break check
      doc.addPage();
      y = 20;
    }
    doc.text(line, 20, y);
    y += 7;
  });
  
  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Generated by AI Co-Teacher | Page ${i} of ${pageCount}`, 20, 285);
  }

  doc.save(filename);
}
